import { useEffect, useState } from 'react'
import { CodeEditor } from './components/CodeEditor'
import { Terminal } from './components/Terminal'
import { hasSensitiveAssignments } from './services/prompt/RepairPromptBuilder'
import { useProgrammer } from './hooks/useProgrammer'
import './App.css'
const labels: Record<string, string> = { unsupported: 'Web Serial 非対応', disconnected: '未接続', 'connection-lost': 'USB切断中', reconnecting: '再接続中', 'requesting-port': 'ポート選択中', opening: '接続中', connected: '接続済み', interrupting: '通常動作へ切替中', 'entering-raw-repl': '通常動作を準備中', 'raw-repl-ready': '通常動作', probing: '機器情報取得中', uploading: 'プログラム更新中', verifying: '構文確認中', starting: '起動中', running: '実行中', 'running-no-marker': '実行中（起動マーカーなし）', stopping: '停止中', stopped: '停止済み', 'setting-boot-mode': '起動モード設定中', resetting: 'リセット中', error: '実行エラー' }
export default function App() {
  const app = useProgrammer(); const [dark, setDark] = useState(() => localStorage.getItem('mpw-theme') !== 'light'); const [wrap, setWrap] = useState(() => localStorage.getItem('mpw-wrap') !== 'false'); const [autoScroll, setAutoScroll] = useState(() => localStorage.getItem('mpw-autoscroll') !== 'false'); const [timestamps, setTimestamps] = useState(false); const [copyNotice, setCopyNotice] = useState<{ text: string; failed: boolean }>(); const ready = app.state === 'raw-repl-ready' || app.state === 'stopped'; const canModifyProgram = ready || app.state === 'running' || app.state === 'running-no-marker'; const busy = !['raw-repl-ready', 'stopped', 'disconnected', 'connection-lost', 'error', 'unsupported', 'running', 'running-no-marker'].includes(app.state)
  useEffect(() => { localStorage.setItem('mpw-theme', dark ? 'dark' : 'light'); localStorage.setItem('mpw-wrap', String(wrap)); localStorage.setItem('mpw-autoscroll', String(autoScroll)); document.documentElement.dataset.theme = dark ? 'dark' : 'light' }, [dark, wrap, autoScroll])
  useEffect(() => { if (!copyNotice) return; const timer = window.setTimeout(() => setCopyNotice(undefined), 4000); return () => window.clearTimeout(timer) }, [copyNotice])
  const copyPrompt = async () => { if (!app.error) return; if (hasSensitiveAssignments(app.source) && !confirm('ソースにpassword、token、SSID等らしき代入があります。内容を確認してコピーする？')) return; try { if (!navigator.clipboard?.writeText) throw new Error('Clipboard APIはHTTPSまたはlocalhostでのみ利用できます。'); await navigator.clipboard.writeText(app.error.repairPrompt); setCopyNotice({ text: '✓ AI修正依頼プロンプトをクリップボードへコピーしたよ。', failed: false }) } catch (error) { const message = error instanceof Error && error.message ? error.message : 'クリップボードへの書込みが許可されませんでした。'; setCopyNotice({ text: `コピーできなかったし: ${message}`, failed: true }) } }
  const stampLog = () => timestamps ? app.log.split(/(?<=\n)/).map(line => `[${new Date().toLocaleTimeString()}] ${line}`).join('') : app.log
  return <main className="app"><header><div><h1>M5NanoC6 MicroPython Web Programmer</h1><p>ブラウザ内だけで動く、Web Serial対応の安全なMicroPython開発ツール</p></div><button onClick={() => setDark(v => !v)}>{dark ? '☀ ライト' : '🌙 ダーク'}</button></header>
    {!app.supported && <div className="notice danger">このブラウザはWeb Serial APIに対応していません。PC版ChromeまたはEdgeを使用してください。</div>}
    <section className="status"><span>Web Serial: {app.supported ? '対応' : '非対応'}</span><span>状態: <strong>{labels[app.state]}</strong></span><span>機器: {app.info.deviceName}</span><span>MicroPython: {app.info.microPythonVersion}</span><span>boot_option: {app.info.bootOption ?? '未取得'}</span></section>
    {app.state === 'connection-lost' && <section className="disconnect-screen" role="alert"><h2>🔌 USB接続が切断されたよ</h2><p>ケーブルとNanoC6の電源を確認してから再接続してね。許可済みの同じポートなら、再接続を試せるし。</p><div><button onClick={app.reconnect}>↻ 許可済みポートへ再接続</button><button onClick={app.connect}>🔌 USB接続を選び直す</button></div><small>再接続できない場合は、OSがポートを再認識するまで少し待ってから「USB接続を選び直す」を押してね。</small></section>}
    <section className="toolbar"><label>bps <input type="number" value={app.baudRate} min="1200" onChange={event => app.setBaudRate(Number(event.target.value))} /></label><button disabled={!app.supported || busy || (app.state !== 'disconnected' && app.state !== 'connection-lost')} onClick={app.connect}>🔌 USB接続</button><button disabled={app.state === 'disconnected' || app.state === 'connection-lost'} onClick={app.disconnect}>切断</button><button disabled={busy || app.state === 'disconnected' || app.state === 'connection-lost'} onClick={app.normalMode}>通常動作に戻す</button><button disabled={!ready} onClick={app.load}>プログラムを読み込む</button><button title="編集内容をmain.pyへ永続保存するだけで、実行はしません。" disabled={!canModifyProgram} onClick={app.write}>プログラム更新</button><button title="編集内容をmain.pyへ保存してから実行します。" disabled={!canModifyProgram} onClick={app.run}>実行</button><button disabled={!['running', 'running-no-marker', 'starting'].includes(app.state)} onClick={app.stop}>■ 停止</button><button disabled={!ready} onClick={() => app.setBoot(0)}>動作OKとして自動起動に設定</button><button disabled={!ready} onClick={() => app.setBoot(1)}>次回起動もプログラムモードに設定</button><button disabled={!ready} onClick={app.reset}>↻ リセット</button></section>
    {app.info.deviceName !== '未接続' && !app.info.nanoC6Confirmed && <div className="notice warn">M5Stack NanoC6として確認できませんでした。標準MicroPython互換モードで続行します。</div>}
    <p className="mode-note">通常動作ではWeb Programmerからプログラムの読込み・更新・実行ができるよ。プログラムモードでは次回起動時にmain.pyを自動実行しない。接続時に通常動作は自動で準備され、実行後などに戻すときだけ「通常動作に戻す」を押してね。</p>
    <section className="columns"><div className="panel"><div className="panel-head"><h2>main.py</h2><label><input type="checkbox" checked={wrap} onChange={event => setWrap(event.target.checked)} /> 自動折返し</label></div><CodeEditor value={app.source} onChange={app.setSource} dark={dark} wrap={wrap} errorLine={app.error?.line} onSave={app.write} onRun={app.run} /></div><div className="right"><div className="panel terminal-panel"><div className="panel-head"><h2>シリアルターミナル</h2><span><label><input type="checkbox" checked={autoScroll} onChange={event => setAutoScroll(event.target.checked)} /> 自動スクロール</label><label><input type="checkbox" checked={timestamps} onChange={event => setTimestamps(event.target.checked)} /> 時刻</label><button onClick={() => app.setLog('')}>消去</button></span></div><Terminal log={stampLog()} dark={dark} autoScroll={autoScroll} /></div>{app.error && <div className="panel error"><h2>⚠ エラー: {app.error.exceptionType}</h2><p>{app.error.message}</p><dl><dt>ステージ</dt><dd>{app.error.stage}</dd><dt>main.py 行</dt><dd>{app.error.line ?? '未特定'} {app.error.codeLine && `: ${app.error.codeLine}`}</dd></dl><pre>{app.error.traceback}</pre><button onClick={copyPrompt}>AI修正依頼プロンプトをコピー</button>{copyNotice && <p className={`copy-notice${copyNotice.failed ? ' failed' : ''}`} role="status">{copyNotice.text}</p>}</div>}</div></section>
    <footer>コード・ログは外部送信しないよ。自動起動は5秒の例外未検出だけでは有効化されないし、実機の動作を確認してからボタンを押してね。復旧が必要ならGPIO9を押したままUSB接続してDownload Modeへ入る。</footer></main>
}
